# Generated by Django 5.1.7 on 2025-04-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrou',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Coordinador', 'Coordinador'), ('Vicerrector', 'Vicerrector')], max_length=50),
        ),
    ]
