# Generated by Django 5.1.7 on 2025-04-19 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_snies', models.IntegerField()),
                ('registro_calificado', models.CharField(max_length=300)),
                ('creditos', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('metodologia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id_proyeccion', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('version', models.CharField(max_length=50)),
                ('proprama', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100)),
                ('cupos_maximos', models.IntegerField()),
                ('grupos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('cod_curso', models.IntegerField()),
                ('semestre', models.CharField(max_length=100)),
                ('nom_curso', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('cupo_max', models.IntegerField()),
                ('no_estudiantes', models.IntegerField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='proyecciones.programa')),
            ],
        ),
        migrations.CreateModel(
            name='ComportamientoCurso',
            fields=[
                ('id_comportamiento', models.AutoField(primary_key=True, serialize=False)),
                ('cod_semestre', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=50)),
                ('nom_curso', models.CharField(max_length=100)),
                ('cod_jornada', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('no_estudiantes', models.IntegerField()),
                ('prom_nota', models.FloatField()),
                ('habilitan', models.IntegerField()),
                ('pierdenh', models.IntegerField()),
                ('pierden_total', models.IntegerField()),
                ('cod_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportamientos', to='proyecciones.curso')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportamientos', to='proyecciones.programa')),
            ],
        ),
    ]
