# Generated by Django 5.1.7 on 2025-04-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyeccion',
            old_name='proprama',
            new_name='programa',
        ),
    ]
