# Generated by Django 5.1.7 on 2025-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0002_rename_proprama_proyeccion_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='programa',
            field=models.CharField(max_length=100),
        ),
    ]
