# Generated by Django 5.1.7 on 2025-05-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0004_alter_curso_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='jornada',
            field=models.CharField(max_length=50),
        ),
    ]
