# Generated by Django 5.1.7 on 2025-05-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0005_alter_curso_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comportamientocurso',
            name='cod_curso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comportamientocurso',
            name='programa',
            field=models.CharField(max_length=100),
        ),
    ]
