# Generated by Django 5.1.7 on 2025-05-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0006_alter_comportamientocurso_cod_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyeccion',
            old_name='cupos_maximos',
            new_name='Cupo_Max',
        ),
        migrations.RenameField(
            model_name='proyeccion',
            old_name='grupos',
            new_name='Grupo',
        ),
        migrations.AddField(
            model_name='proyeccion',
            name='No_Estud',
            field=models.IntegerField(default=0),
        ),
    ]
