# Generated by Django 5.1.7 on 2025-05-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0007_rename_cupos_maximos_proyeccion_cupo_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyeccion',
            old_name='No_Estud',
            new_name='No_Estudiantes',
        ),
    ]
