# Generated by Django 5.1.7 on 2025-05-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0008_rename_no_estud_proyeccion_no_estudiantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyeccion',
            old_name='No_Estudiantes',
            new_name='No_Estud_Final',
        ),
    ]
