# Generated by Django 5.1.7 on 2025-05-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0010_remove_proyeccion_grupo_proyeccion_grupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyeccion',
            old_name='Cupo_Max',
            new_name='cupo_max',
        ),
        migrations.RenameField(
            model_name='proyeccion',
            old_name='No_Estud_Final',
            new_name='no_estud_final',
        ),
    ]
