# Generated by Django 5.1.7 on 2025-05-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecciones', '0011_rename_cupo_max_proyeccion_cupo_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_curso', models.IntegerField()),
                ('semestre', models.CharField(max_length=50)),
                ('cod_semestre', models.IntegerField()),
                ('nom_curso', models.CharField(max_length=100)),
                ('prerrequisito', models.CharField(max_length=100)),
            ],
        ),
    ]
